# Generated by Django 5.2.8 on 2025-11-17 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(max_length=50)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('wall', models.CharField(blank=True, max_length=50)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('block_type', models.CharField(choices=[('boulder', 'Boulder'), ('ruta', 'Ruta')], default='ruta', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('cup', models.CharField(choices=[('kids', 'Kids'), ('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='kids', max_length=12)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decirlo', 'Prefiero no decirlo')], max_length=50)),
                ('distance_climbed', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=30)),
                ('label', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_options', to='api.block')),
            ],
            options={
                'ordering': ['order', 'label'],
                'unique_together': {('block', 'key')},
            },
        ),
        migrations.CreateModel(
            name='BlockScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.block')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_scores', to=settings.AUTH_USER_MODEL)),
                ('score_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.scoreoption')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'block'), name='unique_participant_block')],
            },
        ),
    ]
