# Generated by Django 5.2.8 on 2025-11-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_participant_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
