# Generated by Django 5.2.8 on 2025-12-02 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_participant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockscore',
            name='score_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scoreoption'),
        ),
    ]
